<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
	</array>
	<key>name</key>
	<string>Xenos Internal</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>attribute - match illegal double brackets</string>
			<key>match</key>
			<string>\]\]</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>attribute - match illegal double brackets</string>
			<key>match</key>
			<string>\[\[</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(\{\-\-)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>text - match removed text critic markup</string>
			<key>end</key>
			<string>(?&lt;!\\)(\-\-\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>illegal block crossings</string>
					<key>match</key>
					<string>^\s*((\r\n)|(\n))$</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>match the removed text</string>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>markup.deleted</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(\{\+\+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>text - match added text critic markup</string>
			<key>end</key>
			<string>(?&lt;!\\)(\+\+\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>illegal block crossings</string>
					<key>match</key>
					<string>^\s*((\r\n)|(\n))$</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>match the added text</string>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>markup.inserted</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(\{\&gt;\&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>text - match comment text critic markup</string>
			<key>end</key>
			<string>(?&lt;!\\)(\&lt;\&lt;\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>illegal block crossings</string>
					<key>match</key>
					<string>^\s*((\r\n)|(\n))$</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>match the comment text</string>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>comment.block.markup</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(\{\=\=)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>text - match highlight text critic markup</string>
			<key>end</key>
			<string>(?&lt;!\\)(\=\=\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>illegal block crossings</string>
					<key>match</key>
					<string>^\s*((\r\n)|(\n))$</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>match the comment text</string>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>markup.highlight</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(\{)(?=Part|Chapter|Section|Subsection|Subsubsection|Paragraph|Subparagraph)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>text - match the section headings</string>
			<key>end</key>
			<string>(?&lt;!\\)(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.heading</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>illegal block crossings</string>
					<key>match</key>
					<string>^\s*((\r\n)|(\n))$</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>match the text element typename</string>
					<key>match</key>
					<string>(?&lt;=\{)[^:(\\\{)(\\\})]*(:)?</string>
					<key>name</key>
					<string>support.class.element</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>section name</string>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(\{)(?=List)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>text - match the lists</string>
			<key>end</key>
			<string>(?&lt;!\\)(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.list</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>illegal block crossings</string>
					<key>match</key>
					<string>^\s*((\r\n)|(\n))$</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>match the text element typename</string>
					<key>match</key>
					<string>(?&lt;=\{)[^:(\\\{)(\\\})]*(:)?</string>
					<key>name</key>
					<string>support.class.element</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(\{)(?=Blockquote)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>text - match the quotes</string>
			<key>end</key>
			<string>(?&lt;!\\)(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.quote</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>illegal block crossings</string>
					<key>match</key>
					<string>^\s*((\r\n)|(\n))$</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>match the text element typename</string>
					<key>match</key>
					<string>(?&lt;=\{)[^:(\\\{)(\\\})]*(:)?</string>
					<key>name</key>
					<string>support.class.element</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>text - match the beginning and ending braces</string>
			<key>end</key>
			<string>(?&lt;!\\)(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>illegal block crossings</string>
					<key>match</key>
					<string>^\s*((\r\n)|(\n))$</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>match the text element typename</string>
					<key>match</key>
					<string>(?&lt;=\{)[^:(\\\{)(\\\})]*(:)?</string>
					<key>name</key>
					<string>support.class.element</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>double-quoted strings</string>
			<key>end</key>
			<string>(?&lt;!\\)(")(?!")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.quote</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>illegal block crossings</string>
					<key>match</key>
					<string>^\s*((\r\n)|(\n))$</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>attribute - match the beginning and ending brackets</string>
			<key>end</key>
			<string>(?&lt;!\\)(\])(?!\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>string - match quoted strings</string>
					<key>match</key>
					<string>(?&lt;!\\)"[^"]*"</string>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>illegal block crossings</string>
					<key>match</key>
					<string>^\s*((\r\n)|(\n))$</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>match the attribute typename</string>
					<key>match</key>
					<string>(?&lt;=\[)[^:(\\\[)(\\\])]*(:)?</string>
					<key>name</key>
					<string>support.class.attribute</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>code - match the beginning and ending parentheses</string>
			<key>end</key>
			<string>(?&lt;!\\)(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>double-quoted strings</string>
					<key>match</key>
					<string>(?&lt;!\\)"[^"]*"</string>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>illegal block crossings</string>
					<key>match</key>
					<string>^\s*((\r\n)|(\n))$</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>function name being called</string>
					<key>match</key>
					<string>(?&lt;=\()[^\s(\\\()(\\\))]*</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.xenos.internal</string>
	<key>uuid</key>
	<string>3c7cd947-bc58-454d-9c74-a2c15a8e51fa</string>
</dict>
</plist>
